version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: treeheal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: treeheal_db
      MYSQL_USER: treeheal
      MYSQL_PASSWORD: StrongPass123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data:
